### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by EvenGu** [FuxiaoLiu/VisualNews-Repository#2]
https://github.com/FuxiaoLiu/VisualNews-Repository/blob/cbd07145a91c823bfbfb4a93096e1dacb78b4ab7/main.py#L11

I can get around with `from models.model-name import ...` but I will have to rename all the models in your models folder so that they do not start with numbers. It is not a good practice to name a python file starting with numbers. It will cause errors.

**Comment by FuxiaoLiu** [comment]
Thanks for your comments! Actually I didn’t update the old code since our
model was largely changed. I will update the code.

Even ***@***.***>于2021年4月6日 周二下午11:07写道：
