### ISSUE TITLE
Some modules in your repository are missing？

### ISSUE THREAD

**Issue by chenhaishun** [FuxiaoLiu/VisualNews-Repository#3]
Dear Dr. Liu,
Recently, I read your paper "Visual News: Benchmark and Challenges in News Image Captioning" published in EMNLP, and your excellent work and compact declaration inspired me a lot. But I got some trouble when I try to implement the algorithm proposed in your paper, some modules in your repository are missing. So could you please update you source code if possible? I would be very appreciated if you can help me.

Thanks and regards.@FuxiaoLiu

**Comment by FuxiaoLiu** [comment]
Hi, thanks for your interest. I plan to release the full training code by March 2022. I am now busy with the paper deadline and I will upload the code asap after the deadline.

**Comment by chenhaishun** [comment]
Thanks! A good work I have seen!
